In [79]:
import pandas as pd
import fastapi as app

In [108]:
def idAmazon(df):
    dataframe = pd.read_csv(df)
    for i in dataframe['show_id']:
        dataframe['show_id'] = dataframe['show_id'].replace({i: 'a' + i})
    return dataframe


def idDisney(df):
    dataframe = pd.read_csv(df)
    for i in dataframe['show_id']:
        dataframe['show_id'] = dataframe['show_id'].replace({i: 'd' + i})
    return dataframe


def idHulu(df):
    dataframe = pd.read_csv(df)
    for i in dataframe['show_id']:
        dataframe['show_id'] = dataframe['show_id'].replace({i: 'h' + i})
    return dataframe


def idNetflix(df):
    dataframe = pd.read_csv(df)
    for i in dataframe['show_id']:
        dataframe['show_id'] = dataframe['show_id'].replace({i: 'n' + i})
    return dataframe


def nulaG(df):
    df["rating"] = df["rating"].fillna('g')
    return df


def limpiarfechas(df):
    df["date_added"] = pd.to_datetime(df["date_added"])


def mayuscula(df):
    df=df.apply(lambda x: x.astype(str).str.lower() if(x.dtype == 'object') else x)
    return df

def durationSplit(df):
    new = df["duration"].str.split(" ", n = 1, expand = True)
    df.drop(columns = ["duration"], inplace = True)
    df["duration_int"] = new[0].astype(int)
    df["duration_type"] = new[1].astype(str)

In [98]:
amazon = idAmazon("./Datasets/amazon_prime_titles-score.csv")

In [99]:
disney = idDisney("./Datasets/disney_plus_titles-score.csv")

In [100]:
hulu = idHulu("./Datasets/hulu_titles-score (2).csv")

In [101]:
netflix = idNetflix("./Datasets/netflix_titles-score.csv")

In [102]:
nulaG(amazon)
nulaG(disney)
nulaG(hulu)
nulaG(netflix)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,ns1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",29
1,ns2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",86
2,ns3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,75
3,ns4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",49
4,ns5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,92
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,ns8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",20
8803,ns8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8
8804,ns8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,55
8805,ns8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",7
8806,ns8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,44

In [103]:
limpiarfechas(amazon)
limpiarfechas(disney)
limpiarfechas(hulu)
limpiarfechas(netflix)

In [104]:
mayuscula(amazon)
mayuscula(disney)
mayuscula(hulu)
mayuscula(netflix)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,ns1,movie,dick johnson is dead,kirsten johnson,nan,united states,2021-09-25,2020,pg-13,90 min,documentaries,"as her father nears the end of his life, filmm...",29
1,ns2,tv show,blood & water,nan,"ama qamata, khosi ngema, gail mabalane, thaban...",south africa,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t...",86
2,ns3,tv show,ganglands,julien leclercq,"sami bouajila, tracy gotoas, samuel jouy, nabi...",nan,2021-09-24,2021,tv-ma,1 season,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...,75
3,ns4,tv show,jailbirds new orleans,nan,nan,nan,2021-09-24,2021,tv-ma,1 season,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo...",49
4,ns5,tv show,kota factory,nan,"mayur more, jitendra kumar, ranjan raj, alam k...",india,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...,92
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,ns8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2019-11-20,2007,r,158 min,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",20
8803,ns8804,tv show,zombie dumb,nan,nan,nan,2019-07-01,2018,tv-y7,2 seasons,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",8
8804,ns8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2019-11-01,2009,r,88 min,"comedies, horror movies",looking to survive in a world taken over by zo...,55
8805,ns8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2020-01-11,2006,pg,88 min,"children & family movies, comedies","dragged from civilian life, a former superhero...",7
8806,ns8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,111 min,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,44

In [107]:
durationSplit(amazon)
amazon

TypeError: unhashable type: 'Series'